name: module3_task1

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  module3_task1:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.42.1
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install markdown-link-check
        run: |
          ./node_modules/.bin/markdown-link-check content/posts

      - name: Build project
        run: |
          cd module3_task1
          make build

      - name: Run tests
        run: |
          cd module3_task1
          make test

      - name: Check markdown links
        run: |
          cd module3_task1
          markdown-link-check content/posts

      - name: Display help
        run: |
          cd module3_task1
          make help
